# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Principal1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 503)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.gaussjordan = QtWidgets.QRadioButton(self.centralwidget)
        self.gaussjordan.setObjectName("gaussjordan")
        self.gridLayout.addWidget(self.gaussjordan, 1, 0, 1, 1)
        self.textproceso = QtWidgets.QTextEdit(self.centralwidget)
        self.textproceso.setEnabled(True)
        self.textproceso.setStyleSheet("QTextEdit{border:2px groove #242424;}\n"
"")
        self.textproceso.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textproceso.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textproceso.setReadOnly(True)
        self.textproceso.setObjectName("textproceso")
        self.gridLayout.addWidget(self.textproceso, 1, 1, 9, 1)
        self.otrometodo = QtWidgets.QRadioButton(self.centralwidget)
        self.otrometodo.setObjectName("otrometodo")
        self.gridLayout.addWidget(self.otrometodo, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.textecuaciones = QtWidgets.QTextEdit(self.centralwidget)
        self.textecuaciones.setStyleSheet("QTextEdit{border:2px groove #242424;}")
        self.textecuaciones.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textecuaciones.setReadOnly(True)
        self.textecuaciones.setObjectName("textecuaciones")
        self.gridLayout.addWidget(self.textecuaciones, 6, 0, 1, 1)
        self.graficar = QtWidgets.QPushButton(self.centralwidget)
        self.graficar.setEnabled(False)
        self.graficar.setObjectName("graficar")
        self.gridLayout.addWidget(self.graficar, 7, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.textsolucion = QtWidgets.QTextEdit(self.centralwidget)
        self.textsolucion.setEnabled(True)
        self.textsolucion.setStyleSheet("QTextEdit{border:2px groove #242424;}")
        self.textsolucion.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textsolucion.setReadOnly(True)
        self.textsolucion.setObjectName("textsolucion")
        self.gridLayout.addWidget(self.textsolucion, 9, 0, 2, 1)
        self.guardar = QtWidgets.QPushButton(self.centralwidget)
        self.guardar.setEnabled(False)
        self.guardar.setObjectName("guardar")
        self.gridLayout.addWidget(self.guardar, 10, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Metodo Gauss Jordan"))
        self.label.setToolTip(_translate("MainWindow", "<html><head/><body><p>Metodo</p></body></html>"))
        self.label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ff0000;\">Metodo</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#ff0000;\">Metodo</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ff0000;\">Procedimiento</span></p></body></html>"))
        self.gaussjordan.setText(_translate("MainWindow", "Gauss_Jordan"))
        self.textproceso.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.otrometodo.setText(_translate("MainWindow", "otro metoddo"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ff0000;\">Dimension</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "2x2"))
        self.comboBox.setItemText(1, _translate("MainWindow", "3x3"))
        self.comboBox.setItemText(2, _translate("MainWindow", "4x4"))
        self.comboBox.setItemText(3, _translate("MainWindow", "5x5"))
        self.label_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Metodo</p></body></html>"))
        self.label_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ff0000;\">Metodo</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#ff0000;\">Sistema de Ecuaciones</span></p></body></html>"))
        self.textecuaciones.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.graficar.setToolTip(_translate("MainWindow", "Graficar ecuaciones 2x2 o 3x3"))
        self.graficar.setText(_translate("MainWindow", "Graficar"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ff0000;\">Solucion</span></p></body></html>"))
        self.textsolucion.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.guardar.setToolTip(_translate("MainWindow", "Guarde el proceso obtenido"))
        self.guardar.setText(_translate("MainWindow", "Guardar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
